#!/bin/bash
set -euo pipefail
shopt -s nullglob

PROJECT_ROOT="$PWD"
HOME_DIR="$HOME"

APP_NAME="Bridge2Far"
BUNDLE_ID="com.pimpedpixel.games.bridge2far"
LIBS_DIR="$PROJECT_ROOT/lwjgl3/build/libs"
JPACKAGE_DIR="$PROJECT_ROOT/build/jpackage"
OUTPUT_APP="$HOME_DIR/Development/GameDeployableDevelopment/${APP_NAME}.app"
MAIN_CLASS="com.pimpedpixel.games.lwjgl3.Lwjgl3Launcher"

# Run Gradle tasks to produce the shaded LWJGL jar.
export JAVA_HOME="$HOME/Library/Java/JavaVirtualMachines/azul-17.0.6/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"
./gradlew clean lwjgl3:dist

# Locate the fat jar generated by the lwjgl3 module.
APP_JAR=""
for jar in "$LIBS_DIR"/bridge2far-*.jar; do
  case "$jar" in
    *-mac.jar|*-linux.jar|*-win.jar) continue ;;
  esac
  APP_JAR="$jar"
  break
done

if [[ -z "${APP_JAR}" || ! -f "${APP_JAR}" ]]; then
  echo "Unable to locate the LWJGL jar in lwjgl3/build/libs; build may have failed." >&2
  exit 1
fi

JAR_NAME="$(basename "$APP_JAR")"
APP_VERSION="$(grep -E '^projectVersion=' "$PROJECT_ROOT/gradle.properties" | cut -d'=' -f2 | tr -d '\r')"
APP_VERSION="${APP_VERSION:-1.0.0}"

# Locate a usable .icns icon for macOS packaging.
ICON_PATH=""
ICON_CANDIDATES=(
  "$PROJECT_ROOT/icons/icon.icns"
  "$PROJECT_ROOT/icons/logo.icns"
  "$PROJECT_ROOT/lwjgl3/icons/icon.icns"
  "$PROJECT_ROOT/lwjgl3/icons/logo.icns"
)
for candidate in "${ICON_CANDIDATES[@]}"; do
  if [[ -f "$candidate" ]]; then
    ICON_PATH="$candidate"
    break
  fi
done

if [[ -z "$ICON_PATH" ]]; then
  echo "Could not find an .icns icon (checked: ${ICON_CANDIDATES[*]})." >&2
  exit 1
fi

if [[ ! -x "$JAVA_HOME/bin/jpackage" ]]; then
  echo "jpackage not found in \$JAVA_HOME; install a JDK that ships with jpackage." >&2
  exit 1
fi

# Build the .app image with jpackage.
rm -rf "$JPACKAGE_DIR"
mkdir -p "$JPACKAGE_DIR"

"$JAVA_HOME/bin/jpackage" \
  --type app-image \
  --name "$APP_NAME" \
  --input "$LIBS_DIR" \
  --main-jar "$JAR_NAME" \
  --main-class "$MAIN_CLASS" \
  --java-options "-Xmx1G" \
  --java-options "-XstartOnFirstThread" \
  --app-version "$APP_VERSION" \
  --mac-package-name "$APP_NAME" \
  --mac-package-identifier "$BUNDLE_ID" \
  --icon "$ICON_PATH" \
  --dest "$JPACKAGE_DIR"

# Move the generated .app into the deployment folder.
rm -rf "$OUTPUT_APP"
mv "$JPACKAGE_DIR/${APP_NAME}.app" "$OUTPUT_APP"
echo "Created $OUTPUT_APP"
